### ISSUE TITLE
Export results into file

### ISSUE THREAD

**Issue by WuglyakBolgoink** [xojs/gulp-xo#14]
Hallo @sindresorhus!

I need a function to export results in file, in `gulp-xo` there is no function. So, I created PR #12 to do this.

**Comment by gucong3000** [comment]
in PR #16, we can do it like that
```
gulp.task('default', () =>
	gulp.src('_fixture.js')
		.pipe(xo())
		.pipe(xo.format(null, fs.createWriteStream('xo.log')))
);
```
